title: leehoseok
description: >-
  이호석의 포트폴리오 및 아카이브입니다.
url: "https://lhseok.github.io"
baseurl: ""
github: lhseok
email: lhseok0228@gmail.com

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:title
  drawings:
    output: true
    permalink: /drawings/:title
  pictures:
    output: true
    permalink: /pictures/:title

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: posts
    values:
      layout: post

exclude: [README.md, Gemfile, Gemfile.lock, .gemini, node_modules, vendor]
